[package]
name = "mustui"
version.workspace = true
edition.workspace = true

[dependencies]
tuigreat = { path = "../tuigreat" }
ratatui = { workspace = true }
rodio = "0.19"
mpris-server = "0.8"
tokio = { version = "1", features = ["rt", "sync", "macros"] }
